name: Build And Deploy Cloud Runs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        node-version: [16.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - uses: 'google-github-actions/setup-gcloud@v0'
      - uses: nrwl/nx-set-shas@v3
      - name: Install node_modules
        run: |
          npm i
      - name: Build Apps
        run: |
          nx affected:build
      - name: Deploy Apps
        run: |
          for app in $(nx affected:apps --plain); do
            sh ./sh/deliver.sh develop $app build
            sh ./sh/deliver.sh develop $app push
            sh ./sh/deliver.sh develop $app deploy
          done
