name: Affected Test
on:
  pull_request:
    branches: [main]
env:
  BEFORE_SHA: ${{ github.event.before }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: git fetch origin main
      - name: npm install
        run: npm install
      - name: Run Affected Test-Release
        shell: bash
        run: nx affected:test -- --base=main --head=HEAD --verbose
